language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod 777 ./phpunit.phar

script:
  - ./phpunit.phar
